# Generated by Django 5.2.9 on 2025-12-22 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=5, help_text='Fuel price per gallon in USD', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'db_table': 'fuel_stations',
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_lat_lon'), models.Index(fields=['state', 'city'], name='idx_state_city'), models.Index(fields=['retail_price'], name='idx_price'), models.Index(fields=['is_active', 'state'], name='idx_active_state')],
            },
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(db_index=True, max_length=255)),
                ('end_location', models.CharField(db_index=True, max_length=255)),
                ('route_geometry', models.JSONField(help_text='GeoJSON route geometry')),
                ('fuel_stops', models.JSONField(help_text='List of optimal fuel stops')),
                ('total_distance_miles', models.FloatField()),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fuel_gallons', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Route Cache',
                'verbose_name_plural': 'Route Caches',
                'db_table': 'route_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['start_location', 'end_location'], name='idx_route_locations')],
                'unique_together': {('start_location', 'end_location')},
            },
        ),
    ]
